### ISSUE TITLE
Plugin working only locally for me

### ISSUE THREAD

**Issue by Batista45s** [Protected/EmbyParty#2]
First of all, congratulations on the effort, the plugin works really well, but I am not able to use it externally with Cloudflare's tunnel or Tailscale.

**Comment by Protected** [comment]
Strange. Why are you not able to use it? Please describe the concrete steps you are taking, the result you are seeing, and what you expected to see.

If there are any logs or visible errors, please include them! You can also include screenshots if you like.

Note that except for the external application bridge (optional), Emby Party piggybacks on Emby's native websocket. If Emby functions normally in your setup, there is no reason that I know why Emby Party shouldn't, although since not a lot of people have tried it yet it's always possible there's something else we need to account for.

**Comment by Batista45s** [comment]
The plugin is installed and works fine locally, but when accessed externally, it simply isn't there. There's no error or any indication—it just doesn't appear. I'll run some additional tests later and get back with more information.

**Comment by Protected** [comment]
That sounds like the old appheader may be cached somewhere so the client module isn't actually being loaded by the browser?

You can press ctrl+shift+i (or in some browsers f12) and check if there are any errors logged that correspond to appheader or partyheader. Note that emby itself lets several errors be logged (uncaught exceptions and such) that are not related to this plugin. If the party header is just not there and there are no errors, it's likely the problem above.

**Comment by Batista45s** [comment]
It worked, Cloudflare kept the old appheader in cache. I just had to delete it, and it worked. Thanks for the help!

**Comment by Protected** [comment]
Glad you managed to sort it out! Cacheing in general will always be a problem in unsanctioned client modifications or updates as things currently stand. URLs are passed the Emby version by Emby, so when there is an Emby update the URL becomes different and this should invalidate the cache and result in a smooth update experience. But custom changes do *not* change the Emby version, so the URL doesn't change...

Other than some encoding/decoding/ffmpeg issues that are native to Emby, we haven't been experiencing any known disruptions to Emby Party in the last couple of weeks so be sure to report if you find any new issues!
